### ISSUE TITLE
Issue: DMax Adventure Preview is NOT Programmed for BOTH Sword & Shield!!

### ISSUE THREAD

**Issue by Th3Alic3** [zaksabeast/CaptureSight#67] opened 2020-12-10 17:49 UTC
Hello ZaksBeast,

The actual issue has becomed "muddied" due to the number of "Issue Threads" that I previously started. Please disregard those and refer only to this thread.

**ISSUE:** Capture Sight's Dynamax Adventures previews are configured ONLY to produce data for _Pokémon Sword_
**RESULT:** Capture Sight's Dynamax Adventures previews in _Pokémon Shield_ will experience discrepencies

To demonstrate this: I will be using EdiZon to inject a specific value into the DMax Adventure Rental Team/Pathway SEED on 3 separate saves across both versions. The following SEED will be used for all of the examples:
![image](https://user-images.githubusercontent.com/57371173/101802038-d9150800-3ac3-11eb-8315-62b9332504f8.png)

To keep things simple, I will be using the same number of NPCs in all examples:
![image](https://user-images.githubusercontent.com/57371173/101802078-e4683380-3ac3-11eb-9a99-a4c717ee18e6.png)

The Pokémon Sword & Shield games generate **_ALL_**encounters from SEEDs (regardless of it's the Pathway OR regular Raids in the main game) dynamically independent from user specific variables. This means that if the same SEED value appearing in the same in-game location on every, single copy of the game will produce the same effect.

This means that any two players around the world who happen to find themselves with identical SEEDs for the Pathway SEED will encounter **_100% IDENTICAL_** Rental Team/Pathways!

However, this SEED is subject to the same treatment as all other SEEDs, there is a data off-set Sword & Shield. If you take a SEED from anywhere in the game (regardless of it's the Pathway OR regular Raids in the main game) and plug it into another game it will only be **_100% IDENTICAL_** if the game is the same version.

Example 1:
**VERSION:** Sword
**Trainer ID:** ![image](https://user-images.githubusercontent.com/57371173/101801910-b4209500-3ac3-11eb-9e7e-4dfe5c1a9244.png)

**Capture Sight Rental Team Preview:**
![image](https://user-images.githubusercontent.com/57371173/101802230-0c579700-3ac4-11eb-98f9-b2d816655ca7.png)

Example 2 (Pokémon Shield):
**VERSION:** Shield
**Trainer ID:** ![image](https://user-images.githubusercontent.com/57371173/101802779-ae777f00-3ac4-11eb-8a75-9c8181080b5f.png) *Note: This profile has not collected the Trainer ID card yet as indication of the missing icons. It's just collected the Starter Pokémon.*

**Capture Sight Rental Team Preview:**
![image](https://user-images.githubusercontent.com/57371173/101802928-dc5cc380-3ac4-11eb-8711-b425de75e95c.png)

Example 3 (Pokémon Shield):
**VERSION:** Shield
**Trainer ID:** ![image](https://user-images.githubusercontent.com/57371173/101807665-39a74380-3aca-11eb-9780-3384563d3066.png)

**Capture Sight Rental Team Preview:**
![image](https://user-images.githubusercontent.com/57371173/101807589-22685600-3aca-11eb-9d47-22d65927fa44.png)

**In-Game Rental Team Preview:**
![image](https://user-images.githubusercontent.com/57371173/101807833-6d826900-3aca-11eb-918a-8dfaec8c84b4.png)

- Example 1, 2, 3 all demonstrate that Capture Sight produces the same results for a specific SEED regardless of what version or Trainer ID the player has.

- Example 1 demonstrates Capture Sight produces accurate results for Sword.

- Example 1 & 3 demonstrate that Capture Sight is not factoring in the off-set between Sword & Shield and starts the Rental Team list 1 Pokémon late.

- Example 2 & 3... would (if I advanced Example 2's progress to the Max Lair) would show the identical in-game Rental Teams/Pathways since they are both on Shield. Simularly, if you inject this same SEED into your Sword, you will get the same results as Example 1.

I assume that Capture Sight is programmed for the Sword / Shield offset for the Regular Raids??? The same offset is missing in the code of Capture Sight for the Rental Team/Pathway SEED.

You are extremely unlikely to have reports of issues with _Pokémon Shield_ outside of me. _(From my experience with the cheat code commmunities, I can say with certainity the majority of CFW users are playing on Sword. The simple fact is that it was leaked first and the mass majority of CFW Switch owners are pirating games.)_

I assure you that if you start to test on Shield via the Shield + Expansion Pass game card you will see that off-set of one Pokémon that needs to be accounted for.

**Comment by zaksabeast** [comment] 2020-12-10 19:28
First, I really appreciate you looking into this and trying to debug the problem.  With CaptureSight being a for-fun side project, there are often other things that need my attention and take priority.  Trying to figure out the underlying issue can be a big help!

> I assure you that if you start to test on Shield via the Shield + Expansion Pass game card you will see that off-set of one Pokémon that needs to be accounted for.

I pretty much exclusively test on Shield with the expansion pass since that's my main game.   :slightly_smiling_face: 

CaptureSight isn't actually reading the Pokemon from memory, so there isn't an offset between Sword and Shield.  CaptureSight reads the seed responsible for generating the species, then generates the species.  The game doesn't store the species ahead of time, so this is the only way to know what species a dmax adventure will have before it begins.

The PRNG that is used to determine the Pokemon species is also used for a few other purposes.  If anything the PRNG was used for was calculated incorrectly, it can shift the results.

Since most species in your examples are the same, it shows CaptureSight is reading the initial seed from the correct offset and the issue is in how CaptureSight uses the PRNG to calculate the species.

[I think these lines could be causing the issue](https://github.com/zaksabeast/CaptureSight/blob/master/libcsight/source/csight/Game/SWSH/DmaxAdventure.cpp#L222-L224).  I really should have added a comment to those lines, but if I remember correctly those lines determine the boss Pokemon.  Due to time, I decided to release the last CSight update without adding the boss to the view.

Why would this cause the bug?  The game has a list of Pokemon templates that are used to create the rental, raid, and boss Pokemon.  When choosing a boss Pokemon, the game filters the boss Pokemon in some way (presumably by which Pokemon haven't been caught yet) and generates a random number with the limit being the number of Pokemon remaining in the filter results.  This random number is used to pick a boss template, which is shown to the user at the start of the dmax adventure (so it's the first thing to be generated).

The random number limit in CSight is currently hardcoded, rather than based on a filter like it should be.  That will produce incorrect results.

If anyone wants to help fix this, I'd be more than happy to provide support and offsets to the necessary functions in the game binary.

**Comment by Th3Alic3** [comment] 2020-12-10 19:54
> CaptureSight isn't actually reading the Pokemon from memory, so there isn't an offset between Sword and Shield.
To clarify: I assure you there 100% an off-set between Sword & Shield in the game's programming code. This appears to be what Capture Sight is missing and why only Sword is correct.

> Why would this cause the bug? The game has a list of Pokemon templates that are used to create the rental, raid, and boss Pokemon. When choosing a boss Pokemon, the game filters the boss Pokemon in some way (presumably by which Pokemon haven't been caught yet) and generates a random number with the limit being the number of Pokemon remaining in the filter results. This random number is used to pick a boss template, which is shown to the user at the start of the dmax adventure (so it's the first thing to be generated).

You seem to keep looping back to this notion that there are OTHER random factors... that determine the results. I assure... there are not. It's 100% the result of the the SINGLE UInt64 SEED.

I am WELL over a 500 Raids with the EXACT SAME SINGLE UInt64 SEED.

The following NEVER changes:
- 7 Rental Pokémon
- 10 Pathway Pokémon
- The Pathway Routes
- Location of Berries
- Location of Scientists
- Location of Hikers
- Pokémon offered by each Scientist
- Items offered by each Hiker

I cannot speak for Capture Sight BUT in terms of Pokémon Sword & Shield, there is NO other variables that impact the Dynamax Adventure for those elements. The Legendary has no barring nor do any of the other SEEDs. PERIOD.

**Comment by zaksabeast** [comment] 2020-12-10 23:32
Here's what happens when I force my seed on my Shield with the expansion pass:
![correct-seed](https://user-images.githubusercontent.com/19464008/101841629-ed7cf300-3b0b-11eb-9022-42a72df1000e.jpg)
I'm forcing the same seed that you used on your saves, and I selected 3 NPCs too.

My Shield gets the same results as the Sword game you posted:
![with-many-legends](https://user-images.githubusercontent.com/19464008/101841664-fd94d280-3b0b-11eb-9478-5c4418ab7cb1.jpg)

Here are my results after I use PKHeX to set most of the legends as having been encountered:
![with-few-legends](https://user-images.githubusercontent.com/19464008/101841705-14d3c000-3b0c-11eb-88f0-3ef7d46c6698.jpg)

Because my Shield game originally had the same result as your Sword game, we can deduce:
- There is no offset between Sword and Shield
- Sword and Shield can have the same result

The only difference with the second screenshot is the number of legends I haven't caught, so we can deduce that variable does affect the Pokemon in the dynamax adventure.

The game has a function that basically says, "Give me a random number between 0 and X", where "X" is some number given to the function whenever it's used.  This function is located at `.text + 0x15dc9a0` on Shield v1.3.0.  It's inclusive, so calling `rand(2)` would return 0, 1, or 2.

The function works by:
1. Creating a mask from the inclusive mask by setting all bits (e.g. 2 is `10` in binary, so the mask would be `11` or 3)
1. Invoking the PRNG to get a number
1. Applying the mask to the number
1. If the number is not within the original range (e.g. 0-2), repeat steps 2-4

So the function actually invokes the PRNG multiple times until it has a low enough number.  This loop can be found at `.text + 0x15dca18`.

If Save 1's legend filter results in 16 legends, and Save 2's legend filter results in 2 legends, then there's a higher chance Save 1 will need to call the PRNG more than Save 2 in order to get a random number within the filter limit.

If Save 1 calls the PRNG 1 more time, then the results between Save 1 and Save 2 will shift by 1.  This shift is what we're observing in both of our screenshots.

On another note, hikers use a different PRNG to get their items.  It's possible to randomly get the same set of items multiple times in a row (I have), but within a few tries they do change.  The hiker's items come from a CSPRNG, not the save seeded PRNG that determines species.  This can be tested by setting a breakpoint at that function and testing modified results.

**Comment by Th3Alic3** [comment] 2020-12-11 02:10
> The only difference with the second screenshot is the number of legends I haven't caught

I misunderstood your previous comments about the Legendary Boss as being linked to that specific boss NOT number of Event Flags set to caught... I constantly reset the Event flags (via PKHeX) so I am able to catch all the Legendaries.

This makes perfect sense then the difference between the game saves in my examples as I have not reset flags in that Sword save.

**Comment by zaksabeast** [comment] 2021-10-24 00:46
Closing since dmax adventure is not in the [rewrite](ae0ba44916c623aaf6bf0f9bde85ba7d64794213).

**Closed by zaksabeast** 2021-10-24 00:46 UTC
Labels: bug, help wanted
