### ISSUE TITLE
Atmosphere Update 19.1, it doesn’t work normally

### ISSUE THREAD

**Issue by SoupD** [zaksabeast/CaptureSight#71] opened 2021-04-18 09:57 UTC
Atmosphere Update 19.1, it doesn’t work normally. Can you update it? There will be a box in Chinese to request an update. Thank you

**Comment by zaksabeast** [comment] 2021-04-19 12:22
Thank you for posting this.

Could you please try the [latest release](https://github.com/zaksabeast/CaptureSight/releases/latest) and see if that fixes the problem you're seeing?

**Comment by SoupD** [comment] 2021-04-19 12:44
No, it still doesn’t work, it’s a very sad thing

**Comment by SoupD** [comment] 2021-04-19 12:44
> Thank you for posting this.
> 
> Could you please try the [latest release](https://github.com/zaksabeast/CaptureSight/releases/latest) and see if that fixes the problem you're seeing?

No, it still doesn’t work, it’s a very sad thing

**Comment by zaksabeast** [comment] 2021-04-19 13:55
At first this sounded like it might have been an issue with the latest switch update, but the latest CaptureSight release works on my updated switch, so this must be a different problem.

Here are a few questions that can help figure out what's wrong:
1. What is the specific issue you're having?
2. Could you please post a screenshot of the issue you're having?
3. Could you please post a screenshot of the switch settings page that shows the version you're on? (Just to double check and be extra sure)

**Comment by SoupD** [comment] 2021-04-20 14:18
> At first this sounded like it might have been an issue with the latest switch update, but the latest CaptureSight release works on my updated switch, so this must be a different problem.
> 
> Here are a few questions that can help figure out what's wrong:
> 
> 1. What is the specific issue you're having?
> 2. Could you please post a screenshot of the issue you're having?
> 3. Could you please post a screenshot of the switch settings page that shows the version you're on? (Just to double check and be extra sure)

It worked because I operated it by myself. Thank you. May I have a request? The NRO program has blocks in Chinese, you can update it, thank you!

**Comment by SoupD** [comment] 2021-05-01 10:13
[](url)

> At first this sounded like it might have been an issue with the latest switch update, but the latest CaptureSight release works on my updated switch, so this must be a different problem.
> 
> Here are a few questions that can help figure out what's wrong:
> 
> 1. What is the specific issue you're having?
> 2. Could you please post a screenshot of the issue you're having?
> 3. Could you please post a screenshot of the switch settings page that shows the version you're on? (Just to double check and be extra sure)

Hello, it doesn’t work anymore, there is no response when running Tesla[图片][图片]

**Comment by SoupD** [comment] 2021-05-01 10:15
> At first this sounded like it might have been an issue with the latest switch update, but the latest CaptureSight release works on my updated switch, so this must be a different problem.
> 
> Here are a few questions that can help figure out what's wrong:
> 
> 1. What is the specific issue you're having?
> 2. Could you please post a screenshot of the issue you're having?
> 3. Could you please post a screenshot of the switch settings page that shows the version you're on? (Just to double check and be extra sure)

Hello, it doesn’t work anymore, there is no response when running Tesla
![微信图片_20210501181457](https://user-images.githubusercontent.com/74762398/116779520-32002f80-aaa9-11eb-8404-157e5e7ad707.jpg)
![微信图片_20210501181512](https://user-images.githubusercontent.com/74762398/116779522-34fb2000-aaa9-11eb-8a58-c17717e5d483.jpg)

**Comment by zaksabeast** [comment] 2021-05-12 03:27
Do either of you have any other sysmodules running besides CaptureSight?

**Comment by d-shado** [comment] 2021-05-12 07:58
I tried with no modules and it kinda works.
The problem is SaltyNX, that I use to see FPSs in game.
I said "kinda" because in the applet I have strange key labels (exit, back,
ok), but I think it's a localization problem.

Il mer 12 mag 2021, 05:27 Zak ***@***.***> ha scritto:

**Comment by zaksabeast** [comment] 2021-05-12 12:07
Cool, so it sounds like it works without SaltyNX.

If there are localization issues you'd like to be addressed, opening another issue with any words that are not translated (and possibly their translations) would be greatly appreciated.

**Comment by zaksabeast** [comment] 2021-06-12 11:48
I'm going to close this since there hasn't been activity for a month and the issue appears to have been resolved.

**Closed by zaksabeast** 2021-06-12 11:48 UTC
