### ISSUE TITLE
Black Screen 

### ISSUE THREAD

**Issue by acrylic-s** [zaksabeast/CaptureSight#4] opened 2019-12-20 18:58 UTC
So Im currently using Atmosphere and as I attempt to open CaptureSight with homebrew through the Album so that my game will stay running and it can work as intended, I just end up getting met with  a black screen. If I open CaptureSight with homebrew launched through Hulu or any other app, it actually loads but Im not getting any values here obviously since Pokemon isnt open.

**Comment by Skytso** [comment] 2019-12-20 20:43
I'm having the same issue. No error messages and it'll close out without any problems.

**Comment by zaksabeast** [comment] 2019-12-20 21:16
Hey, thanks for the report - just a few quick questions:
- Which Switch firmware version are you using?
- Which version of Atmosphere are you using?
- When loading CaptureSight, is the Pokemon game already running? (i.e. 1. Boot Switch, 2. Start game, 3. Press Home button and load CaptureSight - it sounds like this is the case, but just making sure)

**Comment by Skytso** [comment] 2019-12-20 22:18
Current version: 9.1.0|AMS 0.10.0

Actually just got an error this time! Error Code: 2168-0002

**Comment by zaksabeast** [comment] 2019-12-20 23:05
I'm not able to replicate this on FW 9.1.0|AMS 0.10.1.

Here are some more questions:
- Is this a digital/installed title or a cartridge?
- Do you have any patches or cheats running at the same time?

**Comment by Skytso** [comment] 2019-12-21 00:12
Cartridge title. As far as I know, I'm not running anything other than just the base game.

**Comment by hectorrshr** [comment] 2019-12-21 00:15
I am having the same issue using SXOS with a digital copy of sword with no patches or cheats running on FW 9.0.0. and SXOS version 2.9.2

**Comment by zaksabeast** [comment] 2019-12-21 05:19
What do you see when you run the CaptureSight attached to this comment?
[CaptureSight.zip](https://github.com/zaksabeast/CaptureSight/files/3991081/CaptureSight.zip)

**Comment by hectorrshr** [comment] 2019-12-21 05:23
When I ran the one that you put in the comment I did get something new!

It says 
"Atmosphere's dhnt:cht is not running!  
Press + to close"

So I am assuming this app is not written for SX OS correct?

**Comment by zaksabeast** [comment] 2019-12-21 05:30
I don't know much about SX OS, so I can't speak to it.

`dmnt:cht` is a service provided by Atmosphere - without it, CaptureSight won't work.

**Comment by greenDarkness** [comment] 2019-12-21 07:59
Had a black screen originally as well. 
However the the CaptureSight you posted here fixed the issue for me.
Really awesome tool by the way, thanks for the release!

**Comment by zaksabeast** [comment] 2019-12-21 15:19
Great, thanks for letting me know.

Also, thanks for using the tool!

**Comment by Skytso** [comment] 2019-12-21 15:52
New version fixed it for me too! Thank you so much.

**Comment by zaksabeast** [comment] 2019-12-21 16:13
Do you see the "Atmosphere's dhnt:cht is not running" message?

**Comment by Skytso** [comment] 2019-12-21 16:17
I do not. It comes up with a list of different pokemon sources (Wild and trade, party, box, etc) but when you click on one it says "Egg - 0/0/0/0/0/0 - Shiny - Party 1" or some similar variant.

Any chance you're on discord? I could stream it so you can see exactly what's going on.

**Comment by zaksabeast** [comment] 2019-12-21 16:25
There's not any Pokemon validation going on at the moment, so that'll happen when there's no Pokemon being read - it sounds like csight can't read your game's memory at the moment.

Do you have this file on your SD card?
```
/atmosphere/contents/010000000000000D/exefs.nsp
```

**Comment by Skytso** [comment] 2019-12-21 16:35
I do indeed.

**Comment by zaksabeast** [comment] 2019-12-21 16:48
Are you able to use Edizon to enable cheats?

Also, I appreciate you helping and answering questions.

**Comment by Skytso** [comment] 2019-12-21 16:52
"No config for this game was found. Editing is disabled."

I've never messed with Edizon before. No idea why it's disabled.

**Comment by greenDarkness** [comment] 2019-12-21 18:08
Do you have the game running while using CaptureSight? I had the same issue but that fixed it for me.

**Comment by Skytso** [comment] 2019-12-21 19:03
I do have the game running and have tried just at the title screen as well as all the way in the game itself.

**Comment by hectorrshr** [comment] 2019-12-21 21:24
I was able to get both SX OS and atmosphere on my sd card and using the updated application works great!

**Comment by zaksabeast** [comment] 2019-12-22 15:14
This one should print out errors from getting dmntcht setup as csight starts.  Can you try running it and let me know if you get an error message?

[CaptureSight.zip](https://github.com/zaksabeast/CaptureSight/files/3992615/CaptureSight.zip)

**Comment by Skytso** [comment] 2019-12-22 16:35
"Atmosphere's dmnt:cht is not running"

**Comment by zaksabeast** [comment] 2019-12-22 18:38
Whoops, I accidentally had a logic error in that build which could cause the wrong error message to be displayed.  Sorry about that - try the one below just to be safe.  I was more thorough when testing the error messages on this one.

[CaptureSight.zip](https://github.com/zaksabeast/CaptureSight/files/3992859/CaptureSight.zip)

Here's what we're looking for:
- "Atmosphere's dmnt:cht is not running" means dmnt:cht is not running
- "Please start a Pokemon game before running CaptureSight" with "dmnt:cht result: 0" means csight knows you're running a game, but doesn't think it's Sword or Shield
- "Please start a Pokemon game before running CaptureSight" with a non-0 dmnt:cht result means something went wrong when csight tried to setup dmnt:cht

**Comment by Skytso** [comment] 2019-12-22 18:54
I have no idea what changed... but it's working now.

**Comment by zaksabeast** [comment] 2019-12-22 18:59
@Skytso I'm glad to hear it!  Thanks for your help troubleshooting potential issues.

@acrylic-s, you were the one who originally opened the issue.  Are you still having troubles, or have the above comments helped resolve the problem?

**Comment by IsometricBananas** [comment] 2019-12-23 20:16
I'm having the same issue Skytso was, I only see shiny 0IV eggs in CaptureSight. Would like me to open a separate issue or should we troubleshoot here?

**Comment by acrylic-s** [comment] 2019-12-23 23:52
Tried the one you posted, and I get "Please start a Pokemon game before running CaptureSight dmnt:cht result: 3328013. 
Am also on 9.1.0|AMS 0.10.0 btw.

**Comment by zaksabeast** [comment] 2019-12-24 03:59
Just to be sure - do you have the game running while using CaptureSight?

**Comment by SuperN0va** [comment] 2019-12-24 19:34
I got the same error code Please start a Pokemon game before running CaptureSight dmnt:cht result: 3328013 during my game running，sys 9.1.0|AMS 0.10.0

**Comment by zaksabeast** [comment] 2019-12-25 00:14
I can't seem to reproduce this unless a game is not running.

- Can you use cheats with EdiZon?
- Are you running a modified or forked version of Atmosphere?

**Comment by Wiifan420** [comment] 2019-12-25 00:29
So will this not work with sx os? Im using an xci and have the CaptureSight from this issue thread and it gives me the error Atmospjeres dmnt:cht is not running. Dmnt:cht result: 0

**Comment by br0wnm6n** [comment] 2019-12-25 01:02
running SXOS here as well. 

Its not showing up in my homebrew (album) area as a program to run. I HAD it installed in sdmc:/switch/CaptureSight/output/CaptureSight.nro by just extracting the folder from the Zip and moving it into the switch directory.

Got it to show up by moving the *.nro file to switch directory so its now:

sdmc:/switch/CaptureSight.nro
sdmc:switch/CaptureSight/output/

Run the program in the homebrew album and it shows a black screen only.

Running 9.1.0
SXOS V2.9.3

**Comment by hectorrshr** [comment] 2019-12-25 01:09
@br0wnm6n you will not be able to use it on SXOS. As the author said this is coded using resources from dmnt:cht. I was running only SXOS before this but I had to run both atmosphere and SXOS to be able to use CaptureSight.

**Comment by br0wnm6n** [comment] 2019-12-25 01:12
@hectorrshr I realize. I did have atmosphere before SX OS. so I'm not sure if thats why mine dosen't give me an error and just have a black screen?

**Comment by Dressah** [comment] 2019-12-25 13:17
I'm using SXOS as well, tried to run both SXOS+Atmosphere, worked for a couple days but now it seems to simple crash my switch at random times and I have to reinstall everything from the start. I've seen a lot of people that had to install atmosphere just to use capture sight, wouldnt be possible to make it work using only SXOS? thanks in advance, great work there <3

**Comment by zaksabeast** [comment] 2019-12-29 18:03
Since this relies on Atmosphere's dmnt:cht, SXOS is something which won't be supported specifically.

With a new release out today, some of you facing troubles may see new warning messages when CaptureSight starts which may help solve your specific issues.

**Comment by SuperN0va** [comment] 2019-12-30 08:49
> I can't seem to reproduce this unless a game is not running.
> 
> * Can you use cheats with EdiZon?
> * Are you running a modified or forked version of Atmosphere?

I can not use cheats with EdiZon
I‘m using the modified version of Atmosphere’

**Comment by zaksabeast** [comment] 2019-12-30 12:50
If you can't use cheats with EdiZon, you most likely won't be able to use this app.  Since both of those require Atmosphere's dmnt:cht to use, if you can't use one you probably can't use the other.

**Comment by wolfgsl** [comment] 2020-01-03 17:14
Would you be willing enhancement for SXOS support?

**Comment by zaksabeast** [comment] 2020-01-18 13:41
I'm closing this issue since there has been no activity in the past half month, and it looks like anyone with an issue is either:
- Not using a supported custom firmware
- Not using CaptureSight while Pokemon Sword or Shield is running

**Closed by zaksabeast** 2020-01-18 13:41 UTC
Labels: bug
